version: "3.9"
services:
  web:
    build: .
    container_name: viper-portable
    ports:
      - '8080:8080'
    networks:
      appnet:
        ipv4_address: 10.10.0.2

  apache:
    image: httpd:latest
    ports:
      - '8081:80'
    volumes:
      - './cyberchef_v9.46.0:/usr/local/apache2/htdocs'

networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.10.0.0/16
