version: "3.9"
services:
  web:
    build: .
    container_name: viper-portable
    ports:
      - '8080:8080'
    networks:
      appnet:
        ipv4_address: 10.10.0.2

networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.10.0.0/16
