version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
#     networks:
#       appnet:
#         ipv4_address: 172.17.0.10

# networks:
#   appnet:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#        - subnet: 172.17.0.0/16
